#!/usr/bin/env bash
# Write packages/web/.env.local from Terraform envs/dev outputs so the Next.js
# frontend talks to Cognito + API Gateway (GovCloud).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEV="$ROOT/infra/envs/dev"
WEB_ENV="$ROOT/packages/web/.env.local"

if [[ ! -f "$DEV/backend.hcl" ]]; then
  echo "Missing $DEV/backend.hcl — run ./infra/scripts/deploy.sh first." >&2
  exit 1
fi

cd "$DEV"
terraform init -input=false -reconfigure -backend-config=backend.hcl >/dev/null

HTTP="$(terraform output -raw http_api_endpoint)"
WS="$(terraform output -raw websocket_api_endpoint)"
POOL="$(terraform output -raw cognito_user_pool_id)"
CLIENT="$(terraform output -raw cognito_client_id)"
ISSUER="$(terraform output -raw cognito_issuer_url)"
REGION="$(terraform output -raw aws_region)"

# API Gateway HTTP is https://… ; browser WS needs wss://…
WS_BROWSER="${WS/wss:\/\//wss://}"
if [[ "$WS" == https://* ]]; then
  WS_BROWSER="${WS/https:\/\//wss://}"
elif [[ "$WS" == http://* ]]; then
  WS_BROWSER="${WS/http:\/\//ws://}"
fi

cat > "$WEB_ENV" <<EOF
# Generated by infra/scripts/sync-web-env.sh — do not commit secrets.
# Local Fastify: delete this file or set NEXT_PUBLIC_AUTH_MODE=local

NEXT_PUBLIC_AUTH_MODE=cognito
NEXT_PUBLIC_API_URL=${HTTP}
NEXT_PUBLIC_WS_URL=${WS_BROWSER}
NEXT_PUBLIC_COGNITO_REGION=${REGION}
NEXT_PUBLIC_COGNITO_USER_POOL_ID=${POOL}
NEXT_PUBLIC_COGNITO_CLIENT_ID=${CLIENT}
NEXT_PUBLIC_COGNITO_ISSUER_URL=${ISSUER}
EOF

echo "Wrote ${WEB_ENV#"$ROOT"/}"
cat "$WEB_ENV" | sed 's/^/  /'
echo
echo "Restart the web app: npm run dev:web"
echo "Open http://127.0.0.1:5173/login"
