# Partial backend — bucket/table/region supplied at init time via backend.hcl
# (generated by infra/scripts/deploy.sh after bootstrap). Do not put secrets here.

terraform {
  backend "s3" {
    key     = "envs/dev/terraform.tfstate"
    encrypt = true
  }
}
